(() => {
"use strict";
const $ = id => document.getElementById(id);
const KEY = "sn-application-tracker-v1";
const PROFILE_KEY = "sn-application-profile-v1";
const safe = v => String(v ?? "").trim();
const escapeHTML = s => String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
let activeTool="cover";
let selectedOpportunity=null;
const toolDefs={
 eligibility:{title:"Eligibility & requirements checker",desc:"Paste the listing description to extract explicit requirements. Mark each item based on your own evidence.",fields:[["title","Opportunity title","text","Selected opportunity"],["description","Opportunity description","textarea","Paste the official description"],["profile","Your relevant qualifications","textarea","Degree, citizenship/residency if relevant, experience, dates, other eligibility facts"]]},
 cover:{title:"Cover / motivation letter writer",desc:"Create an editable first draft using the job requirements and your factual experience.",fields:[["name","Your full name","text","Full name"],["email","Your email","email","name@example.com"],["title","Opportunity title","text","Position or scholarship title"],["institution","Institution / organization","text","Organization name"],["description","Opportunity description","textarea","Paste listing details and selection criteria"],["profile","Your relevant background","textarea","Education, achievements, experience and skills relevant to this opportunity"],["motivation","Why this opportunity?","textarea","Your genuine reasons, goals and relevant interests"]]},
 cv:{title:"CV tailoring assistant",desc:"Identify relevant evidence and suggested edits. Keep all claims accurate and verifiable.",fields:[["title","Opportunity title","text","Position title"],["description","Opportunity description","textarea","Paste the official description"],["profile","Current CV or experience bullets","textarea","Paste CV text, skills, projects, publications and achievements"],["target","Target role / priority","text","e.g. emphasize microbiology research, teaching, grant writing"]]},
 email:{title:"Academic email assistant",desc:"Prepare a professional email for a professor, admissions team, employer or referee.",fields:[["purpose","Email purpose","select",""],["name","Your name","text","Full name"],["recipient","Recipient name / title","text","Professor / Dr / Hiring committee"],["institution","Institution","text","University or organization"],["title","Opportunity title","text","Relevant opportunity"],["description","Context and details","textarea","What you want to ask or communicate"],["profile","Relevant background","textarea","Brief background and reason for contacting them"]]},
 statement:{title:"Academic statement writer",desc:"Start a structured statement. Check the requested format and word limit in the official call.",fields:[["kind","Statement type","select",""],["name","Your name","text","Full name"],["title","Opportunity / program","text","Program or role"],["institution","Institution","text","University or organization"],["description","Opportunity and selection criteria","textarea","Paste the relevant official requirements"],["profile","Your academic / professional background","textarea","Research, teaching, projects, publications, achievements"],["goals","Research, teaching or career goals","textarea","Specific interests, evidence and future plans"]]},
 tracker:{title:"Application tracker",desc:"Save an opportunity, deadline, and application status in this browser.",fields:[["title","Opportunity title","text","Opportunity name"],["institution","Institution","text","University / organization"],["deadline","Deadline","date",""],["url","Official application URL","url","https://"],["status","Status","select",""]]}
};
function fieldHTML(f){const [id,label,type,placeholder]=f; if(type==="select"){let opts=id==="purpose"?[["supervisor","Contact a potential supervisor"],["application","Submit an application"],["referee","Request a recommendation"],["followup","Polite follow-up"],["question","Ask about eligibility or funding"]]:id==="kind"?[["sop","Statement of purpose"],["research","Research statement"],["teaching","Teaching statement"],["intent","Letter of intent"],["personal","Personal statement"],["career","Career goals statement"]]:[["interested","Interested"],["preparing","Preparing documents"],["ready","Ready to submit"],["submitted","Submitted"],["interview","Interview"],["offer","Offer received"],["rejected","Unsuccessful"],["withdrawn","Withdrawn"]];return '<div class="app-field"><label for="app-'+id+'">'+label+'</label><select id="app-'+id+'" name="'+id+'">'+opts.map(o=>'<option value="'+o[0]+'">'+o[1]+'</option>').join("")+'</select></div>';}return '<div class="app-field '+(type==="textarea"?"full":"")+'"><label for="app-'+id+'">'+label+'</label>'+(type==="textarea"?'<textarea id="app-'+id+'" name="'+id+'" placeholder="'+placeholder.replace(/"/g,"&quot;")+'"></textarea>':'<input id="app-'+id+'" name="'+id+'" type="'+type+'" placeholder="'+placeholder.replace(/"/g,"&quot;")+'">')+'</div>';}
function getForm(){const o={};new FormData($("appForm")).forEach((v,k)=>o[k]=safe(v));return o;}
function getTracker(){try{return JSON.parse(localStorage.getItem(KEY)||"[]")}catch{return []}}
function putTracker(rows){localStorage.setItem(KEY,JSON.stringify(rows));renderTracker()}
function toast(msg){let n=document.createElement("div");n.className="app-pill";n.textContent=msg;$("appWorkspace").prepend(n);setTimeout(()=>n.remove(),2600)}
function loadTool(tool,row){activeTool=tool;selectedOpportunity=row||selectedOpportunity;const d=toolDefs[tool];$("appWorkspace").hidden=false;$("appTrackerPanel").hidden=tool==="tracker"?false:true;$("appEyebrow").textContent="SCHOLAR NEWS APPLICATION DESK";$("appWorkspaceTitle").textContent=d.title;$("appWorkspaceDesc").textContent=d.desc;$("appFormFields").innerHTML=d.fields.map(fieldHTML).join("");$("appOutput").hidden=true;
if(row){const vals={title:row.title||"",institution:row.institution||row.organization||"",description:row.description||row.job_description||row.summary||"",deadline:row.deadline||row.application_deadline||"",url:row.source_url||row.url||""};Object.entries(vals).forEach(([k,v])=>{const el=$("app-"+k);if(el&&!el.value)el.value=String(v).slice(0,15000)});}
if(tool==="tracker"){if(row){const f=getTracker();if(!f.some(x=>x.url===(row.source_url||row.url)&&x.title===row.title)){f.unshift({id:Date.now(),title:row.title||"Untitled opportunity",institution:row.institution||row.organization||"",deadline:row.deadline||row.application_deadline||"",url:row.source_url||row.url||"",status:"interested",created:new Date().toISOString()});putTracker(f)}}renderTracker();}
$("appWorkspace").scrollIntoView({behavior:"smooth",block:"start"});}
function makeDraft(tool,v){const date=new Date().toLocaleDateString();const title=v.title||"the advertised opportunity",inst=v.institution||"your institution",name=v.name||"[Your name]",profile=v.profile||"[Add your relevant qualifications, evidence and achievements]",desc=v.description||"[Add specific requirements from the official opportunity]",mot=v.motivation||v.goals||"[Add your genuine motivation and goals]";if(tool==="cover")return name+"\n"+(v.email||"[Your email]")+"\n"+date+"\n\nSelection Committee\n"+inst+"\n\nSubject: Application for "+title+"\n\nDear Selection Committee,\n\nI am writing to express my interest in "+title+" at "+inst+". My background includes "+profile+". I am particularly interested in this opportunity because "+mot+".\n\nThe advertised requirements emphasize "+desc.slice(0,500)+(desc.length>500?"…":"")+". I would welcome the opportunity to contribute my relevant skills and experience while continuing to develop professionally in this area. The examples and achievements in my application materials provide further detail about my suitability.\n\nThank you for considering my application. I would be pleased to provide any additional information required.\n\nYours sincerely,\n"+name+"\n\n[Review and replace every bracketed section; add specific, verifiable examples that demonstrate the selection criteria.]";
if(tool==="cv")return "CV TAILORING REVIEW — "+title+"\n\nPRIORITY AREAS TO COMPARE\n"+desc+"\n\nEVIDENCE FROM YOUR CURRENT CV\n"+profile+"\n\nSUGGESTED NEXT STEPS\n1. Move the most relevant, truthful experience and skills near the top.\n2. Match section headings and terminology to the advertised criteria where accurate.\n3. Rewrite task descriptions as evidence-based achievement bullets: action + scope + outcome.\n4. Include relevant publications, teaching, grants, methods or leadership only when supported by your record.\n5. Remove unrelated detail if it obscures fit; preserve dates and credentials accurately.\n6. Check all required qualifications and documents against the official listing.\n\nTARGET EMPHASIS\n"+(v.target||"[Specify the role's most important criteria]")+"\n\nThis is a review framework, not an automatically verified CV. Do not add experience, skills or results you cannot substantiate.";
if(tool==="email"){const purpose=v.purpose||"application";const subject=purpose==="supervisor"?"Prospective research opportunity inquiry":purpose==="referee"?"Request for a recommendation letter":purpose==="followup"?"Follow-up regarding "+title:"Inquiry regarding "+title;return "Subject: "+subject+"\n\nDear "+(v.recipient||"Professor / Dr [Surname]")+",\n\nI hope you are well. My name is "+name+", and I am contacting you regarding "+title+" at "+inst+".\n\n"+(v.description||"I would appreciate your guidance regarding the opportunity and its application requirements.")+"\n\nBy way of brief introduction, "+(v.profile||"[Add a concise, accurate summary of your background and relevant experience]")+".\n\n"+(purpose==="referee"?"Would you feel comfortable providing a recommendation based on your knowledge of my work? I can share my CV, the opportunity description, the deadline and a short summary of relevant projects to make this easier.":purpose==="followup"?"I am writing to politely follow up on my previous message. I understand you have many commitments, and I appreciate your time.":purpose==="supervisor"?"If my background aligns with your current work, I would be grateful to know whether you may be considering students or researchers in this area.":"Could you please advise on the next steps or clarify any relevant requirements?")+"\n\nThank you for your time and consideration.\n\nKind regards,\n"+name+"\n[Contact information]";}
const kind=v.kind||"sop";const label=({sop:"Statement of Purpose",research:"Research Statement",teaching:"Teaching Statement",intent:"Letter of Intent",personal:"Personal Statement",career:"Career Goals Statement"})[kind]||"Academic Statement";return label.toUpperCase()+"\n"+name+"\n"+title+" — "+inst+"\n\n1. PURPOSE AND FIT\nExplain why this opportunity and institution are a strong match. Refer to specific aims, resources or selection criteria from the official description.\n\n"+desc+"\n\n2. RELEVANT EXPERIENCE AND EVIDENCE\n"+profile+"\n\n3. INTERESTS, APPROACH AND CONTRIBUTION\n"+mot+"\n\n4. FUTURE GOALS\nDescribe realistic short- and long-term goals and how this opportunity will help you pursue them.\n\n5. CONCLUSION\nSummarize fit and intended contribution in a concise closing paragraph.\n\n[Draft scaffold only. Replace each section with specific, truthful examples. Follow the provider's requested format, evidence standards and word limit; remove sections that are not requested.]";}
function requirements(v){const text=v.description||"";const patterns=[["Degree / qualification",/Ph\.?D\.?|doctorate|master'?s|bachelor'?s|degree|qualification/i],["Experience",/years? of experience|experience|postdoctoral|teaching experience/i],["Deadline",/deadline|apply by|applications? (?:close|due)|until \w+ \d{1,2}|closing date/i],["Required documents",/CV|resume|cover letter|motivation letter|statement of purpose|research statement|teaching statement|transcript|recommendation|reference letter/i],["Eligibility / residency",/citizen|citizenship|resident|residency|eligible|eligibility|international applicants/i],["Research / subject fit",/research|discipline|field of study|speciali[sz]ation|subject area/i],["Funding / salary",/funded|funding|stipend|salary|tuition|benefit/i],["Submission route",/apply online|application portal|submit|email.*application|application form/i]];return patterns.filter(([label,re])=>re.test(text)).map(([label])=>label)}
function generate(){const v=getForm();if(activeTool==="eligibility"){const found=requirements(v);const rows=(found.length?found:["No standard requirement patterns detected — review the full listing manually."]).map((x,i)=>'<label class="app-check-row"><input type="checkbox"> <span><strong>'+escapeHTML(x)+'</strong><br><small>Verify the exact condition and your evidence in the official call.</small></span></label>').join("");$("appOutput").hidden=false;$("appOutputLabel").textContent="Requirements checklist";$("appDraft").hidden=true;let existing=$("appRequirementList");if(!existing){existing=document.createElement("div");existing.id="appRequirementList";existing.className="app-checklist";$("appOutput").prepend(existing)}existing.innerHTML=rows+'<p class="app-note">Detected '+found.length+' requirement categories. This is keyword-assisted extraction, not an eligibility decision. The full official rules prevail.</p>';return}
$("appDraft").hidden=false;const draft=makeDraft(activeTool,v);$("appDraft").value=draft;$("appOutput").hidden=false;$("appOutputLabel").textContent=activeTool==="cv"?"CV review notes":"Editable draft";$("appDraft").scrollIntoView({behavior:"smooth",block:"center"});}
function saveDraft(){const v=getForm();const rows=getTracker();const key=(v.title||selectedOpportunity?.title||"Application draft")+"|"+activeTool;let item=rows.find(x=>x.key===key);if(!item){item={id:Date.now(),key,title:v.title||selectedOpportunity?.title||toolDefs[activeTool].title,institution:v.institution||"",deadline:v.deadline||selectedOpportunity?.deadline||"",url:v.url||selectedOpportunity?.source_url||"",status:"preparing",created:new Date().toISOString(),drafts:{}};rows.unshift(item)}item.drafts=item.drafts||{};item.drafts[activeTool]=activeTool==="eligibility"?$("appRequirementList")?.innerText||"":$("appDraft").value;item.updated=new Date().toISOString();putTracker(rows);toast("Saved to this browser's tracker")}
function renderTracker(){const el=$("appTrackerList");if(!el)return;const rows=getTracker();el.innerHTML=rows.length?rows.map(x=>'<div class="app-tracker-item"><div><strong>'+escapeHTML(x.title||"Untitled opportunity")+'</strong><small>'+escapeHTML(x.institution||"Institution not entered")+' · '+escapeHTML(x.deadline||"No deadline set")+'</small><small>Status: '+escapeHTML(x.status||"interested")+'</small>'+(x.url?'<small><a href="'+escapeHTML(x.url)+'" target="_blank" rel="noopener">Official listing ↗</a></small>':"")+'</div><div class="app-actions"><select aria-label="Update status" data-status="'+x.id+'" class="app-status-select">'+["interested","preparing","ready","submitted","interview","offer","rejected","withdrawn"].map(s=>'<option '+(x.status===s?"selected":"")+' value="'+s+'">'+s+'</option>').join("")+'</select><button type="button" class="app-secondary" data-remove="'+x.id+'">Remove</button></div></div>').join(""):'<p class="app-note">No tracked applications yet. Use “Save to tracker” on a draft or select “Application tracker” from an opportunity.</p>'}
function download(){const blob=new Blob([$("appDraft").value],{type:"text/plain;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=((getForm().title||"scholar-news-application").replace(/[^a-z0-9-_]+/gi,"-").slice(0,60)||"application")+".txt";a.click();URL.revokeObjectURL(a.href)}
function bind(){document.querySelectorAll("[data-app-tool]").forEach(b=>b.addEventListener("click",()=>loadTool(b.dataset.appTool,null)));$("appWorkspaceClose").addEventListener("click",()=>$("appWorkspace").hidden=true);$("appForm").addEventListener("submit",e=>{e.preventDefault();generate()});$("appSaveProgress").addEventListener("click",()=>{if(activeTool==="tracker"){const v=getForm();const rows=getTracker();rows.unshift({id:Date.now(),title:v.title,institution:v.institution,deadline:v.deadline,url:v.url,status:v.status||"interested",created:new Date().toISOString()});putTracker(rows);toast("Opportunity saved")}else saveDraft()});$("appSaveDraft").addEventListener("click",saveDraft);$("appDownload").addEventListener("click",download);$("appCopy").addEventListener("click",async()=>{try{await navigator.clipboard.writeText($("appDraft").value);toast("Draft copied")}catch{ $("appDraft").select();toast("Select and copy the draft manually")}});$("appTrackerList").addEventListener("change",e=>{const id=Number(e.target.dataset.status);if(!id)return;const rows=getTracker();const item=rows.find(x=>x.id===id);if(item){item.status=e.target.value;putTracker(rows)}});$("appTrackerList").addEventListener("click",e=>{const id=Number(e.target.dataset.remove);if(id)putTracker(getTracker().filter(x=>x.id!==id))});document.addEventListener("click",e=>{const btn=e.target.closest("#detailBody .apply-tool-button");if(btn){const t=btn.dataset.tool;let row=window.scholarNewsSelectedOpportunity||null;loadTool(t,row)}});const oldShow=window.showScholarNewsApplicationTool;window.showScholarNewsApplicationTool=loadTool;renderTracker();}
document.addEventListener("DOMContentLoaded",bind);
})();